# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2022-08-09 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0083_auto_20220809_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio sugerido')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('caja', models.PositiveIntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recaudacionFondos.Articulo')),
            ],
            options={
                'verbose_name': 'Detalle entrada',
                'verbose_name_plural': 'Detalle entradas',
            },
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recaudacionFondos.Articulo')),
            ],
            options={
                'verbose_name': 'Detalle salida',
                'verbose_name_plural': 'Detalles salidas',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('terminada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150, verbose_name='Correo Electrónico')),
                ('numero', models.PositiveIntegerField(default=0, verbose_name='Número Telefónico')),
                ('direccion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('url', models.URLField(blank=True)),
                ('terminada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
            },
        ),
        migrations.CreateModel(
            name='TipoSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo salida',
                'verbose_name_plural': 'Tipos salidas',
            },
        ),
        migrations.AddField(
            model_name='salida',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recaudacionFondos.TipoSalida'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recaudacionFondos.Proveedor'),
        ),
        migrations.AddField(
            model_name='detallesalida',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salida_detalle', to='recaudacionFondos.Salida'),
        ),
        migrations.AddField(
            model_name='detalleentrada',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='recaudacionFondos.Entrada'),
        ),
        migrations.AddField(
            model_name='detalleentrada',
            name='tarima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Tarima'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recaudacionFondos.Categoria'),
        ),
    ]
