# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 21:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2016, 10, 5, 21, 31, 31, 535168, tzinfo=utc)),
        ),
    ]
