# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 02:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2016, 10, 7, 2, 13, 12, 56744, tzinfo=utc)),
        ),
    ]
