# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='contactomail',
            options={'verbose_name': 'Mail de contacto', 'verbose_name_plural': 'Mails de contactos'},
        ),
        migrations.AlterModelOptions(
            name='contactotelefono',
            options={'verbose_name': 'Teléfono de contacto', 'verbose_name_plural': 'Teléfonos de contactos'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='tipoevento',
            options={'verbose_name': 'Tipo de evento', 'verbose_name_plural': 'Tipos de eventos'},
        ),
        migrations.AlterField(
            model_name='contacto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='fr.Empresa'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='evento',
            field=models.ManyToManyField(related_name='contacto', to='fr.Evento'),
        ),
        migrations.AlterField(
            model_name='contactomail',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail', to='fr.Contacto'),
        ),
        migrations.AlterField(
            model_name='contactotelefono',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefono', to='fr.Contacto'),
        ),
    ]
