# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0002_auto_20161003_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='hora',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2016, 10, 4, 17, 1, 0, 82883, tzinfo=utc)),
        ),
    ]
