# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0003_auto_20161007_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='evento',
            field=models.ManyToManyField(related_name='contact', to='fr.Evento'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2016, 10, 7, 15, 18, 20, 427277, tzinfo=utc)),
        ),
    ]
