# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0005_auto_20161004_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='color',
            field=models.CharField(choices=[('navy', 'azul'), ('aqua', 'aqua'), ('purple', 'Morado'), ('yellow', 'Amarillo'), ('teal', 'turquesa'), ('red', 'rojo'), ('green', 'verde')], default='green', max_length=10),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2016, 10, 4, 20, 8, 55, 524286, tzinfo=utc)),
        ),
    ]
