# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0005_auto_20161007_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='fecha_creacion',
        ),
    ]
