from .software import *
from .dispositivo import *
from .entrada import *
from .desecho import *
from .bodega import *
from .salida import *
from .repuesto import *
from .prestamo import *
from .interno import *
