# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-06 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mye', '0010_auto_20170321_1552'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escuela', '0006_escuela_mapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('asistentes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('cooperantes', models.ManyToManyField(to='mye.Cooperante')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_dh', to=settings.AUTH_USER_MODEL)),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escuela.Escuela')),
            ],
            options={
                'verbose_name': 'Evento de Dejando Huella',
                'verbose_name_plural': 'Eventos de Dejando Huella',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de evento de Dejando Huella',
                'verbose_name_plural': 'Tipos de evento de Dejando Huella',
            },
        ),
        migrations.AddField(
            model_name='eventodh',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dh.TipoEvento'),
        ),
    ]
