# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-06 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventodh',
            name='escuela',
        ),
        migrations.AlterField(
            model_name='eventodh',
            name='asistentes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventodh',
            name='cooperantes',
            field=models.ManyToManyField(blank=True, to='mye.Cooperante'),
        ),
        migrations.AlterField(
            model_name='eventodh',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='eventodh',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='eventodh',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dh.TipoEvento', verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='eventodh',
            name='titulo',
            field=models.TextField(verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='eventodh',
            name='ubicacion',
            field=models.TextField(blank=True, null=True, verbose_name='Ubicación'),
        ),
    ]
