# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-06 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh', '0002_auto_20170606_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoevento',
            name='color',
            field=models.CharField(default='', max_length=12),
        ),
    ]
