# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-06 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh', '0003_tipoevento_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventodh',
            name='fotos',
            field=models.URLField(blank=True, null=True),
        ),
    ]
