# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh', '0004_eventodh_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventodh',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
