# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='dpi',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
