# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='dpi',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
    ]
