# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-08 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_perfil_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='color',
            field=models.CharField(choices=[('#0073b7', 'azul'), ('#39cccc', 'aqua'), ('green', 'verde'), ('#f3c612', 'amarillo'), ('#dd4b39', 'rojo'), ('#605ca8', 'morado'), ('#f012be', 'rosa'), ('#ff851b', 'gris'), ('#777777', 'naranja')], default='#0073b7', max_length=20),
        ),
    ]
