# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171016_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='externo',
            field=models.BooleanField(default=False),
        ),
    ]
