# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscuelaSede',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sede', models.CharField(max_length=125)),
                ('udi', models.CharField(max_length=125)),
                ('escuela', models.CharField(max_length=120)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('participantes', models.PositiveIntegerField()),
                ('capacitador', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Escuela capacitada',
                'db_table': 'v_sede_escuela',
                'verbose_name_plural': 'Escuelas capacitadas',
            },
        ),
    ]
