# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menupagina',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='menupagina',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='menupagina',
            name='path',
        ),
        migrations.AddField(
            model_name='menupagina',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menupagina',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menupagina',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.MenuPagina'),
        ),
        migrations.AddField(
            model_name='menupagina',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menupagina',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menupagina',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
