# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=25)),
                ('lng', models.CharField(max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
    ]
