# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160920_2029'),
        ('main', '0002_auto_20160920_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Perfil')),
                ('menu', models.ManyToManyField(to='main.MenuPagina')),
            ],
        ),
    ]
