# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-06 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_coordenada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenada',
            name='descripcion',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='coordenada',
            name='lat',
            field=models.CharField(max_length=25, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='coordenada',
            name='lng',
            field=models.CharField(max_length=25, verbose_name='Longitud'),
        ),
    ]
