# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menugrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menugrupo',
            name='grupo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
