# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-26 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170606_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoGenerado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('ultima_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo', models.FileField(upload_to='')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('input_url', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Archivos fijos',
                'verbose_name': 'Archivo fijo',
            },
        ),
    ]
