# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_archivogenerado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivogenerado',
            name='archivo',
            field=models.FileField(upload_to='generados/'),
        ),
    ]
