# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160920_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menupagina',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='menugrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_menu', to='auth.Group'),
        ),
    ]
