# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160922_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menugrupo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='menugrupo',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menupagina',
            name='parent',
        ),
        migrations.DeleteModel(
            name='MenuGrupo',
        ),
        migrations.DeleteModel(
            name='MenuPagina',
        ),
    ]
