# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160922_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menugrupo',
            options={'verbose_name': 'Menú de grupo', 'verbose_name_plural': 'menús de grupos'},
        ),
    ]
