# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160922_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Departamento')),
            ],
        ),
        migrations.RemoveField(
            model_name='menugrupo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='menugrupo',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menupagina',
            name='parent',
        ),
        migrations.DeleteModel(
            name='MenuGrupo',
        ),
        migrations.DeleteModel(
            name='MenuPagina',
        ),
    ]
