# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_num', models.IntegerField()),
                ('punteo_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CrHito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('punteo_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('nota_aprobacion', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='crhito',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hito', to='cyd.Curso'),
        ),
        migrations.AddField(
            model_name='crasistencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='cyd.Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='crasistencia',
            unique_together=set([('curso', 'modulo_num')]),
        ),
    ]
