# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-09 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='porcentaje',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
