# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_coordenada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cyd', '0002_curso_porcentaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('capacitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Coordenada')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Municipio')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
    ]
