# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0003_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyd.Curso')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyd.Sede')),
            ],
            options={
                'verbose_name_plural': 'Grupos',
                'verbose_name': 'Grupo',
            },
        ),
    ]
