# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0005_auto_20170117_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cr_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyd.CrAsistencia')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyd.Grupo')),
            ],
            options={
                'verbose_name': 'Calendario de grupos',
                'verbose_name_plural': 'Calendarios de grupos',
            },
        ),
    ]
