# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0006_calendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='dpi',
            field=models.CharField(default='testing', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendario',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cyd.Grupo'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crasistencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cyd.Curso'),
        ),
        migrations.AlterField(
            model_name='crhito',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='cyd.Curso'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tel_casa',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Teléfono de casa'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tel_movil',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Teléfono móvil'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(max_length=150, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together=set([('sede', 'numero')]),
        ),
    ]
