# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-13 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0008_auto_20170606_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='genero',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1),
        ),
    ]
