# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-23 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0009_auto_20170613_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='capacitador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to=settings.AUTH_USER_MODEL),
        ),
    ]
