# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0010_auto_20170623_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Notas de Asistencia',
                'verbose_name': 'Nota de Asistencia',
            },
        ),
        migrations.CreateModel(
            name='NotaHito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Notas de Hito',
                'verbose_name': 'Nota de Hito',
            },
        ),
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together=set([('participante', 'grupo')]),
        ),
        migrations.AddField(
            model_name='notahito',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_hitos', to='cyd.Asignacion'),
        ),
        migrations.AddField(
            model_name='notahito',
            name='cr_hito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyd.CrHito'),
        ),
        migrations.AddField(
            model_name='notaasistencia',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_asistencia', to='cyd.Asignacion'),
        ),
        migrations.AddField(
            model_name='notaasistencia',
            name='gr_calendario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyd.Calendario'),
        ),
    ]
