# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-27 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0011_auto_20170626_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notaasistencia',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_asistencias', to='cyd.Asignacion'),
        ),
        migrations.AlterUniqueTogether(
            name='notaasistencia',
            unique_together=set([('asignacion', 'gr_calendario')]),
        ),
        migrations.AlterUniqueTogether(
            name='notahito',
            unique_together=set([('asignacion', 'cr_hito')]),
        ),
    ]
