# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0012_auto_20170627_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='dpi',
            field=models.CharField(blank=True, db_index=True, max_length=21, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
