# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-24 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0013_auto_20170703_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParGenero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Géneros',
                'verbose_name': 'Género',
            },
        ),
        migrations.AlterField(
            model_name='participante',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cyd.ParGenero'),
        ),
    ]
