# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-28 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0014_auto_20170724_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesorias', to='cyd.Sede')),
            ],
            options={
                'verbose_name_plural': 'Períodos de asesoría',
                'verbose_name': 'Período de asesoría',
            },
        ),
        migrations.AlterField(
            model_name='calendario',
            name='cr_asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyd.CrAsistencia', verbose_name='Asistencia del curso'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='notaasistencia',
            name='gr_calendario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_asociadas', to='cyd.Calendario'),
        ),
    ]
