# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0017_asesoria_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='porcentaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
