# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-22 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0018_auto_20170809_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participantes', to='escuela.Escuela'),
        ),
    ]
