# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-01-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0019_auto_20170822_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
