# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-01-27 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0022_curso_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
