# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-03-26 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0024_auto_20200326_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='abandondo',
            new_name='abandono',
        ),
    ]
