# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-05-07 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0026_recordatoriocalendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='Carpeta Fotos'),
        ),
    ]
