# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-05-11 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0027_sede_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='url_archivos',
            field=models.TextField(blank=True, null=True, verbose_name='Carpeta Archivos'),
        ),
    ]
