# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-05-18 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0028_sede_url_archivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
