# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-10-17 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escuela', '0011_auto_20211017_1152'),
        ('cyd', '0029_sede_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='cyd_asesorias_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='cyd_asignacion_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendario',
            name='cyd_calendario_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crasistencia',
            name='cyd_cr_asistencia_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crhito',
            name='cyd_cr_hito_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='cyd_curso_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='grupos_certificado',
            field=models.IntegerField(choices=[(1, 'Tecnología Básica Nivel Intermedio'), (2, 'NAAT 22 Semanas'), (3, 'NAAT 18 Semanas')], default=1),
        ),
        migrations.AddField(
            model_name='grupo',
            name='cyd_grupo_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notaasistencia',
            name='cyd_nota_asistencia_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notahito',
            name='cyd_nota_hito_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parescolaridad',
            name='cyd_escolaridad_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paretnia',
            name='cyd_etnia_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pargenero',
            name='cyd_genero_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parrol',
            name='cyd_rol_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participante',
            name='cyd_participante_creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sede',
            name='escuela_beneficiada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escuela_beneficiada', to='escuela.Escuela'),
        ),
        migrations.AddField(
            model_name='sede',
            name='tipo_sede',
            field=models.CharField(choices=[('B', 'ESCUELA BENEFICIADA'), ('NB', 'ESCUELA NO BENEFICIADA')], default='B', max_length=2, verbose_name='Tipo de Sede'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='dpi',
            field=models.CharField(blank=True, db_index=True, error_messages={'Unico': 'El dpi ya existe'}, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tel_casa',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Teléfono de casa'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tel_movil',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Teléfono móvil'),
        ),
    ]
