# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2023-07-13 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0030_auto_20220809_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_asignado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Profesion',
                'verbose_name_plural': 'Profesiones',
            },
        ),
        migrations.AddField(
            model_name='participante',
            name='chicas',
            field=models.IntegerField(default=0, verbose_name='niñas'),
        ),
        migrations.AddField(
            model_name='participante',
            name='chicos',
            field=models.IntegerField(default=0, verbose_name='niños'),
        ),
        migrations.AddField(
            model_name='participante',
            name='grado_impartido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cyd.Grado'),
        ),
        migrations.AddField(
            model_name='participante',
            name='profesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cyd.Profesion'),
        ),
    ]
