# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2023-11-24 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0011_auto_20211017_1152'),
        ('cyd', '0031_auto_20230713_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='escuela_beneficiada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escuela_beneficiada', to='escuela.Escuela'),
        ),
        migrations.AddField(
            model_name='sede',
            name='tipo_sede',
            field=models.CharField(choices=[('B', 'ESCUELA BENEFICIADA'), ('NB', 'ESCUELA NO BENEFICIADA')], default='B', max_length=2, verbose_name='Tipo de Sede'),
        ),
    ]
