# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2024-02-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0032_auto_20231209_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
