# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2024-06-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0033_sede_fecha_finalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='finalizada',
            field=models.BooleanField(default=False, verbose_name='Finalizada'),
        ),
    ]
