# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2024-08-08 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cyd', '0034_sede_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='finalizado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, related_name='finalizado', to=settings.AUTH_USER_MODEL),
        ),
    ]
