# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-12 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0011_auto_20211017_1152'),
        ('cyd', '0035_sede_finalizado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_creacion_curso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_desactivacion_curso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='informe_curso',
            field=models.BooleanField(default=False),
        ),
    ]
