from apps.variasApis import views as varias_v 
from django.conf.urls import url, include
urlpatterns = [
 # Creacion de periodos fiscales

  url(
    r'^todo/$',
    varias_v.SubirTodo.as_view(),
    name='revision_datos'
 ),
 url(
    r'^informe/$',
    varias_v.RevionErrores.as_view(),
    name='revisar_errores'
 ),
  url(
    r'^subir/asignaciones/$',
    varias_v.SubirAsignacionesJson.as_view(),
    name='subir_asignaciones'
 ),
 url(
    r'^subir/notaasistencia/$',
    varias_v.SubirNotasAsistenciaJson.as_view(),
    name='subir_nota_asistencia'
 ),
 url(
    r'^subir/notahito/$',
    varias_v.SubirNotasHitosJson.as_view(),
    name='subir_nota_hito'
 ),
 url(
    r'^subir/participantes/2/$',
    varias_v.participantesApi.as_view(),
    name='subir_participantes_2'
 ), 
   url(
      r'^subir/escuelas/2/$',
      varias_v.escuelasApi.as_view(),
      name='subir_escuelas_2'
 ), 
    url(
      r'^subir/equipamiento/2/$',
      varias_v.equipamientoApi.as_view(),
      name='subir_equipamiento_2'
 ), 
     url(
      r'^subir/sede/2/$',
      varias_v.SedeApi.as_view(),
      name='subir_sede_2'
 ),
   url(
      r'^subir/grupo/2/$',
      varias_v.GrupoApi.as_view(),
      name='subir_grupo_2'
 ), 
    url(
      r'^subir/asignacion/2/$',
      varias_v.AsignacionesApi.as_view(),
      name='asignacion_grupo_2'
 ), 
   url(
      r'^subir/notahito/2/$',
      varias_v.HitosApi.as_view(),
      name='asignacion_notahito_2'
 ),
]
