# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Áreas',
                'verbose_name': 'Área',
            },
        ),
        migrations.CreateModel(
            name='EscContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contactos de escuela',
                'verbose_name': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='EscContactoMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='EscContactoRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Roles de contacto',
                'verbose_name': 'Rol de contacto',
            },
        ),
        migrations.CreateModel(
            name='EscContactoTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EscJornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Jornadas',
                'verbose_name': 'Jornada',
            },
        ),
        migrations.CreateModel(
            name='EscModalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Modalidades',
                'verbose_name': 'Modalidad',
            },
        ),
        migrations.CreateModel(
            name='EscNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Niveles',
                'verbose_name': 'Nivel',
            },
        ),
        migrations.CreateModel(
            name='EscPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Planes',
                'verbose_name': 'Plan',
            },
        ),
        migrations.CreateModel(
            name='EscSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Sectores',
                'verbose_name': 'Sector',
            },
        ),
        migrations.CreateModel(
            name='EscStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Statues',
                'verbose_name': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('distrito', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscArea')),
            ],
            options={
                'verbose_name_plural': 'Escuelas',
                'verbose_name': 'Escuela',
            },
        ),
    ]
