# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='EscContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos de escuela',
            },
        ),
        migrations.CreateModel(
            name='EscContactoMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=125)),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail', to='escuela.EscContacto')),
            ],
        ),
        migrations.CreateModel(
            name='EscContactoRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Rol de contacto',
                'verbose_name_plural': 'Roles de contacto',
            },
        ),
        migrations.CreateModel(
            name='EscContactoTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField()),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefono', to='escuela.EscContacto')),
            ],
        ),
        migrations.CreateModel(
            name='EscJornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
            },
        ),
        migrations.CreateModel(
            name='EscModalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='EscNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='EscPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='EscSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='EscStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statues',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('distrito', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscArea')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscJornada')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscModalidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Municipio')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscNivel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscPlan')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscSector')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscStatus')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
            },
        ),
        migrations.AddField(
            model_name='esccontacto',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscContactoRol'),
        ),
    ]
