# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mye', '0001_initial'),
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='cooperante_asignado',
            field=models.ManyToManyField(through='mye.EscuelaCooperante', to='mye.Cooperante'),
        ),
    ]
