# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160929_1724'),
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('distrito', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='escarea',
            options={'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='escjornada',
            options={'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.AlterModelOptions(
            name='escmodalidad',
            options={'verbose_name': 'Modalidad', 'verbose_name_plural': 'Modalidades'},
        ),
        migrations.AlterModelOptions(
            name='escnivel',
            options={'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='escplan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='escsatus',
            options={'verbose_name': 'Stat', 'verbose_name_plural': 'Statues'},
        ),
        migrations.AlterModelOptions(
            name='escsector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectores'},
        ),
        migrations.AddField(
            model_name='escuela',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscArea'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscJornada'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscModalidad'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Municipio'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscNivel'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscPlan'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscSector'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscSatus'),
        ),
    ]
