# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escarea',
            options={'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='escjornada',
            options={'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.AlterModelOptions(
            name='escmodalidad',
            options={'verbose_name': 'Modalidad', 'verbose_name_plural': 'Modalidades'},
        ),
        migrations.AlterModelOptions(
            name='escnivel',
            options={'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='escplan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='escsatus',
            options={'verbose_name': 'Stat', 'verbose_name_plural': 'Statues'},
        ),
        migrations.AlterModelOptions(
            name='escsector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectores'},
        ),
    ]
