# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mye', '0001_initial'),
        ('main', '0001_initial'),
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='cooperante_asignado',
            field=models.ManyToManyField(blank=True, through='mye.EscuelaCooperante', to='mye.Cooperante'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscJornada'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscModalidad'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Municipio'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscNivel'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscPlan'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='proyecto_asignado',
            field=models.ManyToManyField(blank=True, through='mye.EscuelaProyecto', to='mye.Proyecto'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscSector'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscStatus'),
        ),
        migrations.AddField(
            model_name='esccontactotelefono',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefono', to='escuela.EscContacto'),
        ),
        migrations.AddField(
            model_name='esccontactomail',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail', to='escuela.EscContacto'),
        ),
        migrations.AddField(
            model_name='esccontacto',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='escuela.Escuela'),
        ),
        migrations.AddField(
            model_name='esccontacto',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscContactoRol'),
        ),
    ]
