# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mye', '0004_escuelaproyecto'),
        ('escuela', '0002_escuela_cooperante_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='proyecto_asignado',
            field=models.ManyToManyField(through='mye.EscuelaProyecto', to='mye.Proyecto'),
        ),
    ]
