# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_departamento_municipio'),
        ('escuela', '0002_auto_20160928_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('distrito', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscArea')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscJornada')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscModalidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Municipio')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscNivel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscPlan')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscSector')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscSatus')),
            ],
        ),
    ]
