# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_auto_20160929_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EscSatus',
            new_name='EscStatus',
        ),
        migrations.AlterModelOptions(
            name='escstatus',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statues'},
        ),
    ]
