# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_auto_20161003_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EscContactoMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=125)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail', to='escuela.EscContacto')),
            ],
        ),
        migrations.CreateModel(
            name='EscContactoRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EscContactoTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=11)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descripción')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefono', to='escuela.EscContacto')),
            ],
        ),
        migrations.AddField(
            model_name='esccontacto',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscContactoRol'),
        ),
    ]
