# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_auto_20161115_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscPoblacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('alumna', models.IntegerField()),
                ('alumno', models.IntegerField()),
                ('maestra', models.IntegerField()),
                ('maestro', models.IntegerField()),
                ('total_alumno', models.IntegerField(blank=True, null=True)),
                ('total_maestro', models.IntegerField(blank=True, null=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poblaciones', to='escuela.Escuela')),
            ],
            options={
                'verbose_name': 'Población de escuela',
                'verbose_name_plural': 'Poblaciones de escuela',
            },
        ),
    ]
