# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_escpoblacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escpoblacion',
            name='alumna',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='escpoblacion',
            name='alumno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='escpoblacion',
            name='maestra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='escpoblacion',
            name='maestro',
            field=models.IntegerField(default=0),
        ),
    ]
