# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_poblacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poblacion',
            name='escuela',
        ),
        migrations.DeleteModel(
            name='Poblacion',
        ),
    ]
