# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-27 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_coordenada'),
        ('escuela', '0005_auto_20170321_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='mapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Coordenada'),
        ),
    ]
