# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-13 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0006_escuela_mapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='cooperante_asignado',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='proyecto_asignado',
        ),
        migrations.AlterField(
            model_name='escuela',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.EscArea', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='direccion',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono'),
        ),
    ]
