# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-26 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0008_auto_20171016_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escuelas', to='main.Municipio'),
        ),
    ]
