# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-03 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_auto_20180903_1133'),
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='precioestandar',
            unique_together=set([('periodo', 'tipo_dispositivo', 'inventario')]),
        ),
    ]
