# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_auto_20180903_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='precioestandar',
            name='revaluar',
            field=models.BooleanField(default=False),
        ),
    ]
