# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-12 21:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyd', '0008_auto_20170606_1626'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionNaat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=False)),
                ('capacitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignados_naat', to=settings.AUTH_USER_MODEL)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_naat', to='cyd.Participante')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones Naat',
                'verbose_name': 'Asignación Naat',
            },
        ),
    ]
