# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-26 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0010_auto_20171117_0807'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cyd', '0019_auto_20170822_2059'),
        ('naat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionPresencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('ovservaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sesiones Presenciales',
                'verbose_name': 'Sesión presencial',
            },
        ),
        migrations.AlterField(
            model_name='asignacionnaat',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asignacionnaat',
            name='fecha_asignacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionnaat',
            unique_together=set([('participante', 'capacitador', 'activa')]),
        ),
        migrations.AddField(
            model_name='sesionpresencial',
            name='asistentes',
            field=models.ManyToManyField(to='naat.AsignacionNaat'),
        ),
        migrations.AddField(
            model_name='sesionpresencial',
            name='capacitador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_naat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesionpresencial',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.Escuela'),
        ),
    ]
