# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-07 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naat', '0002_auto_20180226_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionpresencial',
            name='asistentes',
            field=models.ManyToManyField(blank=True, to='naat.AsignacionNaat'),
        ),
    ]
