# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-20 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naat', '0004_auto_20180320_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionnaat',
            name='capacitador',
        ),
    ]
