# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-10-17 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('naat', '0005_remove_asignacionnaat_capacitador'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionnaat',
            name='creado_por_asignacion',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesionpresencial',
            name='creado_por_sesion',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
