# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-06-18 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliado', models.CharField(max_length=50, verbose_name='Aliado Coursera')),
            ],
            options={
                'verbose_name': 'Aliado',
                'verbose_name_plural': 'Aliados',
            },
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('invitaciones', models.PositiveIntegerField(default=0, verbose_name='Invitaciones Enviadas')),
                ('miembros', models.PositiveIntegerField(default=0, verbose_name='Miembros Registrados')),
                ('aliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estadísticas', to='coursera.Aliado')),
            ],
            options={
                'verbose_name': 'Monitoreo',
                'verbose_name_plural': 'Estadísticas de monitoreo',
            },
        ),
    ]
