# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-09-02 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, verbose_name='External id')),
                ('enrolled_courses', models.PositiveIntegerField(default=0, verbose_name='Enrolled courses ')),
                ('completed_courses', models.PositiveIntegerField(default=0, verbose_name='Completed courses')),
                ('member', models.IntegerField(choices=[(1, 'INVITED'), (2, 'MEMBER')], default=1, verbose_name='Member state')),
                ('aliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estadísticas_historial', to='coursera.Aliado')),
            ],
            options={
                'verbose_name_plural': 'Historial de monitoreo',
                'verbose_name': 'Historico',
            },
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='aceptacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='graduados',
            field=models.PositiveIntegerField(default=0, verbose_name='No. Graduados'),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='inscritos',
            field=models.PositiveIntegerField(default=0, verbose_name='No. Inscritos'),
        ),
    ]
