# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-10-17 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursera', '0002_auto_20200901_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliado',
            name='creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
