# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-10-16 16:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escuela', '0010_auto_20171117_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visita', models.IntegerField()),
                ('materia', models.IntegerField()),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ('visita',),
                'verbose_name': 'Evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grado', models.CharField(max_length=35, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'Grados',
                'verbose_name': 'Grado',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('color', models.CharField(choices=[('navy', 'azul'), ('aqua', 'aqua'), ('purple', 'Morado'), ('yellow', 'Amarillo'), ('teal', 'turquesa'), ('red', 'rojo'), ('green', 'verde')], default='green', max_length=20)),
                ('icon', models.CharField(default='fa-check-square-o', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'ordering': ('nombre',),
                'verbose_name': 'Materia',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.CharField(max_length=250, verbose_name='nombre del alumno')),
                ('nota', models.IntegerField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='controlNotas.Evaluacion')),
            ],
            options={
                'verbose_name_plural': 'Notas',
                'verbose_name': 'Nota',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Semestres',
                'verbose_name': 'Semestre',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('numero_visita', models.IntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='escuela.Escuela')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='controlNotas.Semestre')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Visitas',
                'verbose_name': 'Visita',
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='controlNotas.Grado'),
        ),
    ]
