# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2023-01-16 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beqt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoTipoBeqt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('usa_triage', models.BooleanField(default=False)),
                ('creada_por', models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de dispositivo',
                'verbose_name_plural': 'Tipos de dispositivo',
            },
        ),
        migrations.AlterField(
            model_name='asignaciontecnico',
            name='tipos',
            field=models.ManyToManyField(blank=True, related_name='tipos_disponibles_beqt', to='beqt.DispositivoTipoBeqt'),
        ),
        migrations.AlterField(
            model_name='dispositivobeqt',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beqt.DispositivoTipoBeqt'),
        ),
        migrations.AlterField(
            model_name='entradadetallebeqt',
            name='tipo_dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_entrada_beqt', to='beqt.DispositivoTipoBeqt'),
        ),
        migrations.AlterField(
            model_name='paquetetipobeqt',
            name='tipo_dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beqt.DispositivoTipoBeqt', verbose_name='Tipos de dispositivo'),
        ),
        migrations.AlterField(
            model_name='solicitudmovimientobeqt',
            name='tipo_dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beqt.DispositivoTipoBeqt'),
        ),
        migrations.AddIndex(
            model_name='dispositivotipobeqt',
            index=models.Index(fields=['slug'], name='beqt_dispos_slug_7c0b3d_idx'),
        ),
    ]
