# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2023-01-19 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0084_auto_20230110_2101'),
        ('beqt', '0002_auto_20230116_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargadorLaptopBeqt',
            fields=[
                ('dispositivobeqt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='beqt.DispositivoBeqt')),
                ('indice', models.PositiveIntegerField(editable=False, unique=True)),
                ('voltaje', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cargador de laptop',
                'verbose_name_plural': 'Cargadores de laptops',
            },
            bases=('beqt.dispositivobeqt',),
        ),
        migrations.CreateModel(
            name='DispositivoRedBeqt',
            fields=[
                ('dispositivobeqt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='beqt.DispositivoBeqt')),
                ('indice', models.PositiveIntegerField(editable=False, unique=True)),
                ('cantidad_puertos', models.PositiveIntegerField(blank=True, null=True)),
                ('velocidad', models.PositiveIntegerField(blank=True, null=True)),
                ('puerto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.DispositivoPuerto')),
            ],
            options={
                'verbose_name': 'Dispositivo de red',
                'verbose_name_plural': 'Dispositivos de red',
            },
            bases=('beqt.dispositivobeqt',),
        ),
        migrations.CreateModel(
            name='RegletaBeqt',
            fields=[
                ('dispositivobeqt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='beqt.DispositivoBeqt')),
                ('indice', models.PositiveIntegerField(editable=False, unique=True)),
                ('conexiones', models.PositiveIntegerField(blank=True, null=True)),
                ('voltaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.DispositivoMedida')),
            ],
            options={
                'verbose_name': 'Regleta',
                'verbose_name_plural': 'Regletas',
            },
            bases=('beqt.dispositivobeqt',),
        ),
        migrations.CreateModel(
            name='UpsBeqt',
            fields=[
                ('dispositivobeqt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='beqt.DispositivoBeqt')),
                ('indice', models.PositiveIntegerField(editable=False, unique=True)),
                ('conexiones', models.PositiveIntegerField(blank=True, null=True)),
                ('voltaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.DispositivoMedida')),
            ],
            options={
                'verbose_name': 'Ups',
                'verbose_name_plural': 'Ups',
            },
            bases=('beqt.dispositivobeqt',),
        ),
    ]
