# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2023-02-08 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beqt', '0005_auto_20230207_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regletabeqt',
            name='voltaje',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Voltaje'),
        ),
        migrations.AlterField(
            model_name='upsbeqt',
            name='voltaje',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Voltaje'),
        ),
    ]
