# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2023-02-11 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beqt', '0006_auto_20230208_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesspointbeqt',
            options={'ordering': ['indice'], 'verbose_name': 'Access Point', 'verbose_name_plural': 'Access Point'},
        ),
        migrations.AlterModelOptions(
            name='cargadorlaptopbeqt',
            options={'ordering': ['indice'], 'verbose_name': 'Cargador de laptop', 'verbose_name_plural': 'Cargadores de laptops'},
        ),
        migrations.AlterModelOptions(
            name='dispositivoredbeqt',
            options={'ordering': ['indice'], 'verbose_name': 'Dispositivo de red', 'verbose_name_plural': 'Dispositivos de red'},
        ),
        migrations.AlterModelOptions(
            name='regletabeqt',
            options={'ordering': ['indice'], 'verbose_name': 'Regleta', 'verbose_name_plural': 'Regletas'},
        ),
        migrations.AlterModelOptions(
            name='upsbeqt',
            options={'ordering': ['indice'], 'verbose_name': 'Ups', 'verbose_name_plural': 'Ups'},
        ),
        migrations.AddField(
            model_name='laptopbeqt',
            name='cargador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargador_laptop_beqt', to='beqt.CargadorLaptopBeqt', verbose_name='Cargador'),
        ),
        migrations.AddIndex(
            model_name='regletabeqt',
            index=models.Index(fields=['indice'], name='beqt_reglet_indice_a96f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspointbeqt',
            index=models.Index(fields=['indice'], name='beqt_access_indice_d58444_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivoredbeqt',
            index=models.Index(fields=['indice'], name='beqt_dispos_indice_85d7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='upsbeqt',
            index=models.Index(fields=['indice'], name='beqt_upsbeq_indice_e6662f_idx'),
        ),
        migrations.AddIndex(
            model_name='cargadorlaptopbeqt',
            index=models.Index(fields=['indice'], name='beqt_cargad_indice_8608d3_idx'),
        ),
    ]
