# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2023-11-20 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beqt', '0007_auto_20230210_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivobeqt',
            name='codigo_rti',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='codigo rti'),
        ),
    ]
