# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2024-02-22 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beqt', '0008_dispositivobeqt_codigo_rti'),
    ]

    operations = [
        migrations.AddField(
            model_name='regletabeqt',
            name='regulador',
            field=models.BooleanField(default=False, verbose_name='Con regulador:'),
        ),
    ]
