# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2024-05-28 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beqt', '0009_regletabeqt_regulador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectorTabletBeqt',
            fields=[
                ('dispositivobeqt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='beqt.DispositivoBeqt')),
                ('indice', models.PositiveIntegerField(editable=False, unique=True)),
                ('compatibilidad', models.CharField(blank=True, max_length=80, null=True, verbose_name='Compatibilidad')),
                ('color', models.CharField(blank=True, max_length=80, null=True, verbose_name='Color')),
                ('material', models.CharField(blank=True, max_length=80, null=True, verbose_name='Material')),
                ('dimensiones', models.CharField(blank=True, max_length=80, null=True, verbose_name='Dimensiones')),
            ],
            options={
                'db_table': 'dispositivo_protector_tablet_beqt',
                'verbose_name_plural': 'Protectores Tablets',
                'ordering': ['indice'],
                'verbose_name': 'Protector Tablet',
            },
            bases=('beqt.dispositivobeqt',),
        ),
        #Altera la tabla de dispositivo_protector_tablet_beqt, para que no se uft8mb4 y no tenga probelmas con llaves foranes, agreado manuelamente
        migrations.RunSQL(
            "ALTER TABLE dispositivo_protector_tablet_beqt CONVERT TO CHARACTER SET latin1 COLLATE latin1_swedish_ci;",
            reverse_sql="ALTER TABLE dispositivo_protector_tablet_beqt CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
        ),
        migrations.AlterField(
            model_name='regletabeqt',
            name='regulador',
            field=models.BooleanField(default=False, verbose_name='Con regulador'),
        ),
        migrations.AddIndex(
            model_name='protectortabletbeqt',
            index=models.Index(fields=['indice'], name='dispositivo_indice_fe39d2_idx'),
        ),
        migrations.AddField(
            model_name='tabletbeqt',
            name='protector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protector_tablets_beqt', to='beqt.ProtectorTabletBeqt', verbose_name='Protector'),
        ),
    ]
