# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipo'},
        ),
        migrations.AlterModelOptions(
            name='estadoequipo',
            options={'verbose_name': 'Estado del Equipo', 'verbose_name_plural': 'Estados del Equipo'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='salida',
            options={'verbose_name': 'Salida', 'verbose_name_plural': 'Salidas'},
        ),
        migrations.AlterModelOptions(
            name='tipoentrada',
            options={'verbose_name': 'Tipo de Entrada', 'verbose_name_plural': 'Tipos de Entrada'},
        ),
        migrations.AlterModelOptions(
            name='tipoproveedor',
            options={'verbose_name': 'Tipo de Proveedor', 'verbose_name_plural': 'Tipos de Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='tiposalida',
            options={'verbose_name': 'Tipo de Salida', 'verbose_name_plural': 'Tipos de Salidas'},
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='direccionn',
            new_name='direccion',
        ),
    ]
