# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Perfil'),
        ),
        migrations.DeleteModel(
            name='Tecnico',
        ),
    ]
