# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0002_auto_20161011_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='kardex.Equipo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kardex.EstadoEquipo')),
            ],
        ),
        migrations.RemoveField(
            model_name='salida',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='no_entrada',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='kardex.Equipo'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='salida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidaequipo', to='kardex.Salida'),
        ),
    ]
