# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0003_auto_20161026_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaequipo',
            name='estado',
        ),
        migrations.AlterField(
            model_name='salidaequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipo', to='kardex.Equipo'),
        ),
        migrations.AlterField(
            model_name='salidaequipo',
            name='salida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salida', to='kardex.Salida'),
        ),
    ]
