# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-29 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0004_auto_20161109_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='salidaequipo',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='salidaequipo',
            name='salida',
        ),
        migrations.AlterModelOptions(
            name='estadoequipo',
            options={'verbose_name': 'Estado del equipo', 'verbose_name_plural': 'Estados del equipo'},
        ),
        migrations.AlterModelOptions(
            name='tipoentrada',
            options={'verbose_name': 'Tipo de entrada', 'verbose_name_plural': 'Tipos de entrada'},
        ),
        migrations.AlterModelOptions(
            name='tipoproveedor',
            options={'verbose_name': 'Tipo de Proveedor', 'verbose_name_plural': 'Tipos de Proveedore'},
        ),
        migrations.AlterModelOptions(
            name='tiposalida',
            options={'verbose_name': 'Tipo de salida', 'verbose_name_plural': 'Tipos de salida'},
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='tipo_entrada',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='nombre_equipo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='estadoequipo',
            old_name='estado_del_equipo',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='tipo_de_proveedor',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='tipo_salida',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='tipoproveedor',
            old_name='tipo_de_proveedor',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='tipoentrada',
            name='tipo_de_entrada',
        ),
        migrations.RemoveField(
            model_name='tiposalida',
            name='tipo_de_salida',
        ),
        migrations.AddField(
            model_name='tipoentrada',
            name='tipo',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiposalida',
            name='tipo',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salida',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.DeleteModel(
            name='SalidaEquipo',
        ),
        migrations.AddField(
            model_name='salidadetalle',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_salida', to='kardex.Equipo'),
        ),
        migrations.AddField(
            model_name='salidadetalle',
            name='salida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='kardex.Salida'),
        ),
    ]
