# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-30 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0005_auto_20170829_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='terminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='kardex.Proveedor'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha',
            field=models.DateField(),
        ),
    ]
