# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-08 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0006_auto_20170830_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'verbose_name_plural': 'Detalles de entrada',
                'verbose_name': 'Detalle de entrada',
            },
        ),
        migrations.AlterModelOptions(
            name='salidadetalle',
            options={'verbose_name': 'Detalle de salida', 'verbose_name_plural': 'Detalles de salida'},
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='precio',
        ),
        migrations.AlterUniqueTogether(
            name='salidadetalle',
            unique_together=set([('salida', 'equipo')]),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='kardex.Entrada'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_entrada', to='kardex.Equipo'),
        ),
    ]
