# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-08 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0007_auto_20170908_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='terminada',
            field=models.BooleanField(default=False),
        ),
    ]
