# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-25 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0008_entrada_terminada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadetalle',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='entradadetalle',
            unique_together=set([('entrada', 'equipo')]),
        ),
    ]
