# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0009_auto_20170925_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadetalle',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=9, null=True),
        ),
    ]
