# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-01 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0050_auto_20190301_0828'),
        ('kardex', '0010_auto_20180529_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='inventario_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='inventario.Entrada'),
        ),
    ]
