# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-01 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0011_entrada_inventario_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='inventario_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario', to='inventario.Entrada'),
        ),
    ]
