# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-01 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0012_auto_20190301_0849'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entradadetalle',
            unique_together=set([]),
        ),
    ]
