# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-04 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0052_solicitudmovimiento_rechazar'),
        ('kardex', '0013_auto_20190301_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='inventario_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario_salida', to='inventario.SalidaInventario'),
        ),
    ]
