# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0052_solicitudmovimiento_rechazar'),
        ('kardex', '0014_salida_inventario_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='inventario_entrada',
        ),
        migrations.AddField(
            model_name='salida',
            name='inventario_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario_salida', to='inventario.SolicitudMovimiento'),
        ),
    ]
