# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-04 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0015_auto_20190304_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='inventario_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_salida', to='inventario.SolicitudMovimiento'),
        ),
    ]
