# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-10-17 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kardex', '0018_auto_20200504_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estadoequipo',
            name='creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipoentrada',
            name='creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipoproveedor',
            name='creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiposalida',
            name='creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
