# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0006_escuela_mapa'),
        ('kalite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Visita',
                'verbose_name': 'Tipo de Visita',
            },
        ),
        migrations.AlterModelOptions(
            name='indicador',
            options={'verbose_name': 'Indicador', 'verbose_name_plural': 'Indicadores'},
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grado',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='color',
            field=models.CharField(choices=[('aqua', 'aqua'), ('green', 'green'), ('yellow', 'yellow'), ('red', 'red'), ('purple', 'purple')], default='aqua', max_length=20),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='icon',
            field=models.CharField(default='fa-check-square-o', max_length=25),
        ),
        migrations.AddField(
            model_name='visita',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de fin'),
        ),
        migrations.AddField(
            model_name='visita',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AddField(
            model_name='visita',
            name='numero',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='visita',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punteo',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='kalite.Evaluacion'),
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='nombre',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterUniqueTogether(
            name='punteo',
            unique_together=set([('evaluacion', 'indicador')]),
        ),
        migrations.AddField(
            model_name='visita',
            name='tipo_visita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kalite.TipoVisita'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='visita',
            unique_together=set([('escuela', 'numero')]),
        ),
        migrations.AddField(
            model_name='tipovisita',
            name='rubricas',
            field=models.ManyToManyField(to='kalite.Rubrica'),
        ),
    ]
