# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalite', '0003_auto_20170829_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='alcanzados',
            field=models.PositiveIntegerField(default=1, verbose_name='Estudiantes alcanzados'),
        ),
        migrations.AddField(
            model_name='grado',
            name='total_ejercicios',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de ejercicios'),
        ),
        migrations.AddField(
            model_name='grado',
            name='total_estudiantes',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de estudiantes'),
        ),
    ]
