# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-20 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name_plural': 'Tipos de laboratorios',
                'verbose_name': 'Tipo de laboratorio',
            },
        ),
        migrations.CreateModel(
            name='SoftwareItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=100)),
                ('sistema_operativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Software para equipo',
                'verbose_name': 'Software para equipo',
            },
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='equipo_uniforme',
            field=models.BooleanField(default=True, verbose_name='El equipo es uniforme'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='marca_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios', to='ie.MarcaItem'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='servidor_local',
            field=models.BooleanField(default=False, verbose_name='Posee servidor local'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='tipo_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratorios', to='ie.TipoItem', verbose_name='Tipo de equipo'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios', to='escuela.Escuela'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='fotos_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link a fotos (GDrive)'),
        ),
    ]
