# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-23 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0008_auto_20171016_0835'),
        ('ie', '0002_auto_20171019_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fotos_link', models.URLField(blank=True, null=True, verbose_name='Link a fotos')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ie_validaciones', to='escuela.Escuela')),
                ('requerimientos', models.ManyToManyField(blank=True, to='ie.Requerimiento')),
            ],
            options={
                'verbose_name': 'Validacion',
                'verbose_name_plural': 'Validacions',
            },
        ),
        migrations.CreateModel(
            name='ValidacionVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('requisitos', models.ManyToManyField(blank=True, to='ie.Requerimiento')),
            ],
            options={
                'verbose_name': 'Versión de validación',
                'verbose_name_plural': 'Versiones de validaciónes',
            },
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='cantidad_computadoras',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de computadoras'),
        ),
        migrations.AddField(
            model_name='validacion',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ie.ValidacionVersion'),
        ),
    ]
