# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-04 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20171016_1118'),
        ('ie', '0003_auto_20171023_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacion',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='validacion',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de fin'),
        ),
        migrations.AddField(
            model_name='validacion',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organizacion'),
        ),
    ]
