# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ie', '0004_auto_20171104_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
    ]
