# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-12 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=125, verbose_name='Nombre del Donante')),
                ('pagina_web', models.URLField(blank=True, verbose_name='Pagina Web')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('fax', models.IntegerField(blank=True, null=True, verbose_name='Fax')),
                ('referido', models.CharField(blank=True, max_length=70, null=True, verbose_name='Referido')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('nit', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero de Nit')),
            ],
            options={
                'verbose_name': 'Donante',
                'verbose_name_plural': 'Donantes',
            },
        ),
        migrations.CreateModel(
            name='DonanteContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=125, verbose_name='Nombre')),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Donante')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='DonanteTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo de Donante')),
            ],
            options={
                'verbose_name': 'Tipo de Donante',
                'verbose_name_plural': 'Tipos de Donantes',
            },
        ),
        migrations.CreateModel(
            name='MailCrm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=25, verbose_name='Correo Electrónico')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.DonanteContacto')),
                ('donante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Donante')),
            ],
            options={
                'verbose_name': 'Correo  Electrónico',
                'verbose_name_plural': 'Correos Electrónicos',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Contacto')),
                ('fecha_bodega', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de Ingreso a Bodega')),
                ('fecha_carta', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de Creación de Carta')),
                ('recibo_contable', models.BooleanField(verbose_name='Se entrego Recibo Contable')),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Donante', verbose_name='Donante')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='OfertaHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Histórico de Ofertas')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Oferta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Oferta',
                'verbose_name_plural': 'Históricos de Ofertas',
            },
        ),
        migrations.CreateModel(
            name='OfertaTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta_tipo', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Oferta')),
            ],
            options={
                'verbose_name': 'Tipo de Oferta',
                'verbose_name_plural': 'Tipos de Ofertas',
            },
        ),
        migrations.CreateModel(
            name='TelefonoCrm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número Telefónico')),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Código de País')),
                ('area', models.IntegerField(blank=True, null=True, verbose_name='Código de Área')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.DonanteContacto')),
                ('donante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Donante')),
            ],
            options={
                'verbose_name': 'Telefono',
                'verbose_name_plural': 'Telefonos',
            },
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OfertaTipo'),
        ),
        migrations.AddField(
            model_name='donante',
            name='tipo_donante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.DonanteTipo'),
        ),
    ]
