# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-26 16:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donantecontacto',
            name='donante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='crm.Donante'),
        ),
        migrations.AlterField(
            model_name='mailcrm',
            name='donante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='crm.Donante'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='donante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='crm.Donante', verbose_name='Donante'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_bodega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso a Bodega'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_carta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Creación de Carta'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2018, 4, 26), verbose_name='Fecha de Contacto'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibido', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por'),
        ),
        migrations.AlterField(
            model_name='ofertahistorico',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Historico de Ofertas'),
        ),
        migrations.AlterField(
            model_name='ofertahistorico',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='crm.Oferta'),
        ),
        migrations.AlterField(
            model_name='telefonocrm',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='crm.DonanteContacto'),
        ),
        migrations.AlterField(
            model_name='telefonocrm',
            name='donante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='crm.Donante'),
        ),
    ]
