# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180427_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2018, 5, 9), verbose_name='Fecha de Contacto'),
        ),
    ]
