# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180509_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Contacto'),
        ),
    ]
