# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-10-17 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_auto_20180517_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='creado_por',
            field=models.ForeignKey(blank=True, default=49, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donantetipo',
            name='creado_por',
            field=models.ForeignKey(blank=True, default=49, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ofertatipo',
            name='creado_por',
            field=models.ForeignKey(blank=True, default=49, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
