# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-08-12 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20211017_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=2, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='donante',
            name='tratamiento',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZACIONAL', 'Organizacional')], default='INDIVIDUAL', max_length=40, verbose_name='Tratamiento del Donante'),
        ),
    ]
