# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 20:26
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='codigo_qr',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='qr_dispositivo'),
        ),
    ]
