# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-28 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_dispositivo_codigo_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.IntegerField()),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='inventario.Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Tarima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarimas', to='inventario.Sector')),
            ],
        ),
        migrations.AddField(
            model_name='nivel',
            name='pasillo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveles', to='inventario.Pasillo'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tarima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='inventario.Tarima'),
        ),
    ]
