# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-28 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0003_auto_20180528_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesechoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Salida de desecho',
                'verbose_name_plural': 'Salidas de desecho',
            },
        ),
        migrations.CreateModel(
            name='DesechoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Empresa de desecho',
                'verbose_name_plural': 'Empresas de desecho',
            },
        ),
        migrations.CreateModel(
            name='DesechoSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Peso (libras)')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.DesechoEmpresa')),
            ],
            options={
                'verbose_name': 'Salida de desecho',
                'verbose_name_plural': 'Salidas de desecho',
            },
        ),
        migrations.CreateModel(
            name='DispositivoFalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_falla', models.TextField(verbose_name='Descripción de la falla')),
                ('descripcion_solucion', models.TextField(blank=True, null=True, verbose_name='Descripción de la solución')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('terminada', models.BooleanField(default=False)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallas', to='inventario.Dispositivo')),
                ('reparada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fallas_reparadas', to=settings.AUTH_USER_MODEL)),
                ('reportada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fallas_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DispositivoFalla',
                'verbose_name_plural': 'DispositivoFallas',
            },
        ),
        migrations.AlterModelOptions(
            name='dispositivorepuesto',
            options={'verbose_name': 'Repuesto de dispositivo', 'verbose_name_plural': 'Repuestos de dispositivo'},
        ),
        migrations.AddField(
            model_name='desechodetalle',
            name='desecho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventario.DesechoSalida'),
        ),
        migrations.AddField(
            model_name='desechodetalle',
            name='entrada_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.EntradaDetalle'),
        ),
    ]
