# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20180528_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='desechosalida',
            name='en_creacion',
            field=models.BooleanField(default=True, verbose_name='En creación'),
        ),
        migrations.AddField(
            model_name='sector',
            name='codigo_qr',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='qr_sector'),
        ),
        migrations.AddField(
            model_name='tarima',
            name='codigo_qr',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='qr_tarima'),
        ),
        migrations.AlterField(
            model_name='desechosalida',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='inventario.DesechoEmpresa'),
        ),
    ]
