# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20180529_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desechodetalle',
            options={'verbose_name': 'Detalle de salida de desecho', 'verbose_name_plural': 'Detalles de salida de desecho'},
        ),
        migrations.AddField(
            model_name='desechodetalle',
            name='tipo_dispositivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_desecho', to='inventario.DispositivoTipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sector',
            name='codigo_qr',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, editable=False, null=True, upload_to='qr_sector'),
        ),
    ]
