# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20180530_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desechosalida',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Peso (libras)'),
        ),
        migrations.AlterField(
            model_name='desechosalida',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
