# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-11 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escuela', '0010_auto_20171117_0807'),
        ('inventario', '0007_auto_20180605_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoPaquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paquetes_aprobados', to=settings.AUTH_USER_MODEL)),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DispositivoPaquete',
                'verbose_name_plural': 'DispositivoPaquetes',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('indice', models.PositiveIntegerField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paquete de salida',
                'verbose_name_plural': 'Paquetes de salida',
            },
        ),
        migrations.CreateModel(
            name='SalidaInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('en_creacion', models.BooleanField(default=True, verbose_name='En creación')),
                ('entrega', models.BooleanField(default=True, verbose_name='Es entrega')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to=settings.AUTH_USER_MODEL)),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='escuela.Escuela')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
            },
        ),
        migrations.CreateModel(
            name='SalidaTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de salida',
                'verbose_name_plural': 'Tipos de salida',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='valido',
            field=models.BooleanField(default=True, verbose_name='Válido'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='codigo_qr',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='qr_repuestos'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='tarima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repuestos', to='inventario.Tarima'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='valido',
            field=models.BooleanField(default=True, verbose_name='Válido'),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='tipo_salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.SalidaTipo'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='dispositivos',
            field=models.ManyToManyField(related_name='paquetes', through='inventario.DispositivoPaquete', to='inventario.Dispositivo'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='inventario.SalidaInventario'),
        ),
        migrations.AddField(
            model_name='dispositivopaquete',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion', to='inventario.Dispositivo'),
        ),
        migrations.AddField(
            model_name='dispositivopaquete',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion', to='inventario.Paquete'),
        ),
        migrations.AlterUniqueTogether(
            name='paquete',
            unique_together=set([('salida', 'indice')]),
        ),
    ]
