# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-14 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0008_auto_20180611_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_revision', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comentarios de revisión',
                'verbose_name': 'Comentario de revisión',
            },
        ),
        migrations.CreateModel(
            name='RevisionSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(default=django.utils.timezone.now)),
                ('anotaciones', models.TextField(blank=True, null=True)),
                ('aprobada', models.BooleanField(default=False)),
                ('revisado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Revisiones de salida',
                'verbose_name': 'Revisión de salida',
            },
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='necesita_revision',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='revisionsalida',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones', to='inventario.SalidaInventario'),
        ),
        migrations.AddField(
            model_name='revisioncomentario',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='inventario.RevisionSalida'),
        ),
    ]
