# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-19 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0010_auto_20180614_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.ManyToManyField(blank=True, related_name='tipos_disponibles', to='inventario.DispositivoTipo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asignaciones de técnicos',
                'verbose_name': 'Asignacion de técnico',
            },
        ),
        migrations.CreateModel(
            name='CambioEtapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Dispositivo')),
                ('etapa_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_final', to='inventario.DispositivoEtapa')),
                ('etapa_inicial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_inicio', to='inventario.DispositivoEtapa')),
            ],
            options={
                'verbose_name_plural': 'Cambios de etapa',
                'verbose_name': 'Cambio de etapa',
            },
        ),
        migrations.CreateModel(
            name='PaqueteTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombre del tipo')),
                ('tipo_dispositivo', models.ManyToManyField(to='inventario.DispositivoTipo', verbose_name='Tipos de dispositivo')),
            ],
            options={
                'verbose_name_plural': 'Tipos de paquete',
                'verbose_name': 'Tipo de paquete',
            },
        ),
        migrations.CreateModel(
            name='SolicitudMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('cantidad', models.PositiveIntegerField()),
                ('terminada', models.BooleanField(default=False)),
                ('autorizada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_movimiento', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_movimiento', to=settings.AUTH_USER_MODEL)),
                ('etapa_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_final', to='inventario.DispositivoEtapa')),
                ('etapa_inicial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_inicial', to='inventario.DispositivoEtapa')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.DispositivoTipo')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de movimiento',
                'verbose_name': 'Solicitud de movimiento',
            },
        ),
        migrations.AlterModelOptions(
            name='dispositivopaquete',
            options={'verbose_name': 'Asignación Dispositivo - Paquete', 'verbose_name_plural': 'Asignaciones Dispositivo - Paquete'},
        ),
        migrations.AddField(
            model_name='paquete',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cambioetapa',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios', to='inventario.SolicitudMovimiento'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='tipo_paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='inventario.PaqueteTipo'),
        ),
    ]
