# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-20 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_auto_20180619_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontecnico',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_dispositivos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cambioetapa',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_etapa', to='inventario.Dispositivo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='estado',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.DispositivoEstado'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='etapa',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.DispositivoEtapa'),
        ),
    ]
