# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-25 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0012_auto_20180620_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='inventario.Dispositivo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios', to='inventario.DispositivoEstado')),
            ],
            options={
                'verbose_name_plural': 'Cambios de estado',
                'verbose_name': 'Cambio de estado',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('devuelto', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_creados', to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='inventario.Dispositivo')),
                ('prestado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Préstamos',
                'verbose_name': 'Préstamo',
            },
        ),
        migrations.AlterField(
            model_name='revisionsalida',
            name='anotaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Anotaciones generales'),
        ),
        migrations.AlterField(
            model_name='revisionsalida',
            name='fecha_revision',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de revisión'),
        ),
        migrations.AlterField(
            model_name='salidainventario',
            name='necesita_revision',
            field=models.BooleanField(default=True, verbose_name='Necesita revisión'),
        ),
    ]
