# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-03 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auto_20180625_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.DispositivoEstado'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='etapa',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.DispositivoEtapa'),
        ),
    ]
