# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-07 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_auto_20180903_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
