# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-07 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_auto_20180907_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadetalle',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
