# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_auto_20180907_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadetalle',
            name='dispositivos_creados',
            field=models.BooleanField(default=False, verbose_name='dispositivo_creado'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='repuestos_creados',
            field=models.BooleanField(default=False, verbose_name='repuesto_creado'),
        ),
    ]
