# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-13 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_auto_20180910_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='entrada_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_dispositivos', to='inventario.EntradaDetalle'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='entrada_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_repuesto', to='inventario.EntradaDetalle'),
        ),
        migrations.AlterField(
            model_name='entradadetalle',
            name='dispositivos_creados',
            field=models.BooleanField(default=False, verbose_name='Dispositivos creados'),
        ),
        migrations.AlterField(
            model_name='entradadetalle',
            name='repuestos_creados',
            field=models.BooleanField(default=False, verbose_name='Repuestos creados'),
        ),
    ]
