# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-17 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_auto_20180913_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='impreso',
            field=models.BooleanField(default=False, verbose_name='Impreso'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='impreso',
            field=models.BooleanField(default=False, verbose_name='Impreso'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='impreso',
            field=models.BooleanField(default=False, verbose_name='Impreso'),
        ),
    ]
