# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_auto_20180916_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadetalle',
            name='qr_dispositivo',
            field=models.BooleanField(default=False, verbose_name='Imprimir Qr Dispositivo'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='qr_repuestos',
            field=models.BooleanField(default=False, verbose_name='Imprimir Qr Repuesto'),
        ),
    ]
