# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-21 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_auto_20180919_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='factura',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
