# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-25 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0021_entrada_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmovimiento',
            name='recibida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudmovimiento',
            name='recibida_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recibida_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
