# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-02 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180517_1512'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0022_auto_20180925_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_revision', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de revisión de salida',
                'verbose_name_plural': 'Comentarios de revisión de salida',
            },
        ),
        migrations.CreateModel(
            name='SalidaEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Estado de salida',
                'verbose_name_plural': 'Estados de salida',
            },
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiario', to='crm.Donante'),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='reasignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reasignar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salidatipo',
            name='necesita_revision',
            field=models.BooleanField(default=True, verbose_name='Necesita revisión'),
        ),
        migrations.AddField(
            model_name='salidacomentario',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='inventario.SalidaInventario'),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estados', to='inventario.SalidaEstado'),
        ),
    ]
