# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-09 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_auto_20180925_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('dispositivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.Dispositivo')),
                ('indice', models.PositiveIntegerField(editable=False, unique=True)),
                ('cantidad_puertos', models.PositiveIntegerField(blank=True, null=True)),
                ('velocidad', models.PositiveIntegerField(blank=True, null=True)),
                ('puerto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.DispositivoPuerto')),
                ('velocidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.DispositivoMedida')),
            ],
            options={
                'verbose_name': 'Access Point',
                'verbose_name_plural': 'Access Point',
            },
            bases=('inventario.dispositivo',),
        ),
        migrations.AddField(
            model_name='entradatipo',
            name='contenedor',
            field=models.BooleanField(default=False),
        ),
    ]
