# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-11 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_auto_20181009_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmovimiento',
            name='desecho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudmovimiento',
            name='devolucion',
            field=models.BooleanField(default=False),
        ),
    ]
