# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-08 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_auto_20181008_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidainventario',
            name='entrada',
            field=models.ManyToManyField(blank=True, null=True, related_name='tipo_entrada', to='inventario.Entrada'),
        ),
    ]
