# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_auto_20181008_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidainventario',
            name='entrada',
        ),
        migrations.AddField(
            model_name='paquete',
            name='entrada',
            field=models.ManyToManyField(blank=True, null=True, related_name='tipo_entrada', to='inventario.Entrada'),
        ),
    ]
