# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-10 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_auto_20181009_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidatipo',
            name='especial',
            field=models.BooleanField(default=False, verbose_name='especial'),
        ),
    ]
