# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-12 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0029_salidatipo_especial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionsalida',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tecnicos', to=settings.AUTH_USER_MODEL),
        ),
    ]
