# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-12 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_auto_20181009_1531'),
        ('inventario', '0030_revisionsalida_tecnico'),
    ]

    operations = [
    ]
