# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-12 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_auto_20181011_1420'),
        ('inventario', '0030_revisionsalida_tecnico'),
    ]

    operations = [
    ]
