# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-17 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_merge_20181012_1513'),
        ('inventario', '0031_merge_20181012_1409'),
    ]

    operations = [
    ]
