# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-23 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_merge_20181017_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='tipo_dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamo_tipo', to='inventario.DispositivoTipo'),
        ),
    ]
