# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-23 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_prestamo_tipo_dispositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de Prestamo',
                'verbose_name_plural': 'Tipos de Prestamo',
            },
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tipo_dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamo_dispositivo', to='inventario.DispositivoTipo'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo_prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamo_tipo', to='inventario.PrestamoTipo'),
        ),
    ]
