# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-05 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_auto_20181023_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_estimada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
