# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-05 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_prestamo_fecha_estimada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='dispositivo',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='dispositivo',
            field=models.ManyToManyField(related_name='prestamos', to='inventario.Dispositivo'),
        ),
    ]
