# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-07 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_auto_20181105_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesechoDispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('desecho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_dispositivos', to='inventario.DesechoSalida')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desecho', to='inventario.Dispositivo')),
            ],
            options={
                'verbose_name': 'Dispositivo de desecho',
                'verbose_name_plural': 'Dispositivos de desecho',
            },
        ),
        migrations.AddField(
            model_name='desechodetalle',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='desechodetalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
