# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-21 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0037_auto_20181107_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='servidor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
