# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-14 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0042_dispositivo_descripcion'),
        ('inventario', '0042_auto_20190213_1529'),
    ]

    operations = [
    ]
