# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-22 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0043_merge_20190214_1106'),
        ('inventario', '0043_merge_20190220_0729'),
    ]

    operations = [
    ]
