# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-21 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpe', '0021_auto_20180309_1119'),
        ('inventario', '0043_merge_20190214_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainventario',
            name='garantia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='garantias', to='tpe.Garantia'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='ram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
