# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0044_auto_20190221_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadetalle',
            name='enviar_kardex',
            field=models.BooleanField(default=False, verbose_name='enviar kardex'),
        ),
        migrations.AlterField(
            model_name='salidainventario',
            name='garantia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='garantias', to='tpe.TicketSoporte'),
        ),
    ]
