# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0044_merge_20190222_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivotipo',
            name='conta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='ram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
