# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-25 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0045_auto_20190225_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadetalle',
            name='ingresado_kardex',
            field=models.BooleanField(default=False, verbose_name='Guardar en kardex'),
        ),
        migrations.AlterField(
            model_name='dispositivotipo',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entradadetalle',
            name='enviar_kardex',
            field=models.BooleanField(default=False, verbose_name='kardex'),
        ),
    ]
