# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-26 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0010_auto_20180529_1547'),
        ('inventario', '0046_auto_20190225_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadetalle',
            name='estado_kardex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_kardex', to='kardex.EstadoEquipo'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='proveedor_kardex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_kardex', to='kardex.Proveedor'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='tipo_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_entrada_kardex', to='kardex.TipoEntrada'),
        ),
    ]
