# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-27 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0047_auto_20190226_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadetalle',
            name='tipo_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_entrada', to='kardex.TipoEntrada'),
        ),
    ]
