# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-27 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0010_auto_20180529_1547'),
        ('inventario', '0048_auto_20190227_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradadetalle',
            name='tipo_entrada',
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='tipo_entrada_kardex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_entrada_kardex', to='kardex.TipoEntrada'),
        ),
    ]
