# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-01 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0049_auto_20190227_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradadetalle',
            name='estado_kardex',
        ),
        migrations.RemoveField(
            model_name='entradadetalle',
            name='proveedor_kardex',
        ),
        migrations.RemoveField(
            model_name='entradadetalle',
            name='tipo_entrada_kardex',
        ),
    ]
