# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-04 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0051_auto_20190301_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmovimiento',
            name='rechazar',
            field=models.BooleanField(default=False),
        ),
    ]
