# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-05 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0045_auto_20190222_1229'),
        ('inventario', '0053_solicitudmovimiento_salida_kardex'),
    ]

    operations = [
    ]
