# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-05 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0054_solicitudmovimiento_entrada_kardex'),
        ('inventario', '0045_auto_20190222_1229'),
    ]

    operations = [
    ]
