# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0055_merge_20190305_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='caja',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='aprobado_kardex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paquete',
            name='desactivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teclado',
            name='caja',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='pulgadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='ram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
