# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-06 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0054_merge_20190305_0707'),
        ('inventario', '0055_merge_20190305_1420'),
    ]

    operations = [
    ]
