# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-06 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0056_merge_20190306_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='caja',
            field=models.CharField(default='caja 1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teclado',
            name='caja',
            field=models.CharField(default='caja 1', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desechodetalle',
            name='entrada_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_entrada', to='inventario.EntradaDetalle'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='pulgadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='ram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
