# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0058_auto_20190306_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='desechosalida',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
