# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-08 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0059_desechosalida_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainventario',
            name='no_salida',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='salidatipo',
            name='equipamiento',
            field=models.BooleanField(default=False, verbose_name='equipamiento'),
        ),
        migrations.AddField(
            model_name='salidatipo',
            name='renovacion',
            field=models.BooleanField(default=False, verbose_name='equipamiento'),
        ),
        migrations.AddField(
            model_name='salidatipo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
