# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-11 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0059_desechosalida_url'),
        ('inventario', '0056_auto_20190307_0939'),
    ]

    operations = [
    ]
