# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-12 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0060_auto_20190308_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamotipo',
            name='dias',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
