# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-12 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0061_prestamotipo_dias'),
        ('inventario', '0060_merge_20190311_0752'),
    ]

    operations = [
    ]
