# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-12 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0061_merge_20190312_1537'),
        ('inventario', '0061_prestamotipo_dias'),
    ]

    operations = [
    ]
