# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-13 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0062_merge_20190312_1542'),
        ('inventario', '0062_merge_20190312_1550'),
    ]

    operations = [
    ]
