# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-15 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0063_dispositivotipo_kardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradatipo',
            name='especial',
            field=models.BooleanField(default=False),
        ),
    ]
