# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-26 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mye', '0014_usuariocooperante'),
        ('inventario', '0064_entradatipo_especial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainventario',
            name='cooperante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cooperante', to='mye.Cooperante'),
        ),
    ]
