# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-18 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0064_entradatipo_especial'),
        ('inventario', '0063_merge_20190313_1225'),
    ]

    operations = [
    ]
