# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-10 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0065_salidainventario_cooperante'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmovimiento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
