# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-28 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0065_salidainventario_cooperante'),
        ('inventario', '0065_merge_20190318_0824'),
    ]

    operations = [
    ]
