# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0066_solicitudmovimiento_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmovimiento',
            name='no_salida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salida_inventario', to='inventario.SalidaInventario'),
        ),
    ]
