# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0066_solicitudmovimiento_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Clase de dispositivo',
                'verbose_name_plural': 'Clases de dispositivo',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clase_dispositivos', to='inventario.DispositivoClase'),
        ),
    ]
