# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-14 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0066_merge_20190328_1411'),
        ('inventario', '0066_solicitudmovimiento_observaciones'),
    ]

    operations = [
    ]
