# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-25 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0067_auto_20190613_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionBitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Regristro Bitacora',
                'verbose_name_plural': 'Registros de Bitacora',
            },
        ),
        migrations.CreateModel(
            name='SolicitudBitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviado', models.BooleanField(default=False)),
                ('accion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacora_accion', to='inventario.AccionBitacora')),
                ('numero_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_movimiento', to='inventario.SolicitudMovimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacoras',
            },
        ),
    ]
