# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-02 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0069_auto_20190625_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdd',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
    ]
