# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-10 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0070_hdd_asignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesechoComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_revision', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('desecho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_desecho', to='inventario.DesechoSalida')),
            ],
            options={
                'verbose_name': 'Comentario de rechazo de desecho',
                'verbose_name_plural': 'Comentarios de rechazo de desecho',
            },
        ),
        migrations.AlterModelOptions(
            name='revisionsalida',
            options={'verbose_name': 'Revisión de salida en contabilidad', 'verbose_name_plural': 'Revisiones de salida en contabilidad'},
        ),
        migrations.AlterModelOptions(
            name='salidacomentario',
            options={'verbose_name': 'Comentario de revisión de salida control de calidad', 'verbose_name_plural': 'Comentarios de revisión de salida control de calidad'},
        ),
    ]
