# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-10 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0071_auto_20190710_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='desechocomentario',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desecho_rechazado', to='inventario.Dispositivo'),
        ),
        migrations.AddField(
            model_name='desechocomentario',
            name='entrada_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_entrada_rechazar', to='inventario.EntradaDetalle'),
        ),
    ]
