# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-12 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0072_auto_20190710_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='desechosalida',
            name='comprobante',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
