# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-25 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0074_desechosalida_codigo_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepuestoComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_revision', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_repuesto_dispositivo', to='inventario.Dispositivo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_repuesto', to='inventario.Repuesto')),
            ],
            options={
                'verbose_name': 'Comentario de repuesto',
                'verbose_name_plural': 'Comentarios de repuestos',
            },
        ),
    ]
