# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0075_repuestocomentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainventario',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
