# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-06 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0075_repuestocomentario'),
        ('inventario', '0067_solicitudmovimiento_no_salida'),
    ]

    operations = [
    ]
