# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-09-04 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0076_salidainventario_url'),
        ('inventario', '0076_merge_20190806_1204'),
    ]

    operations = [
    ]
