# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-01-29 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0077_merge_20190904_1601'),
        ('inventario', '0067_merge_20190514_0758'),
    ]

    operations = [
    ]
