# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-02-16 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0078_merge_20200129_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainventario',
            name='capacitada',
            field=models.BooleanField(default=False, verbose_name='Capacitada'),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='meses_garantia',
            field=models.BooleanField(default=False, verbose_name='6 meses de Garantia'),
        ),
    ]
