# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-02-18 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0079_auto_20210216_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='servidor',
            field=models.BooleanField(default=False),
        ),
    ]
