# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-10-17 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0081_auto_20211016_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioestado',
            name='creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cambioetapa',
            name='creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='descuentoentrada',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='desechodetalle',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='desechodispositivo',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='desechoempresa',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispositivoclase',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispositivoestado',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispositivoetapa',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispositivomedida',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispositivomodelo',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispositivopuerto',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispositivotipo',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entradaestado',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entradatipo',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monitortipo',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paquetetipo',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prestamotipo',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='puertotipo',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repuestocomentario',
            name='creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repuestoestado',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='revisioncomentario',
            name='creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salidacomentario',
            name='creado_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salidaestado',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salidatipo',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sector',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='software',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='softwaretipo',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarima',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipored',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='versionsistema',
            name='creada_por',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
