# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2022-08-09 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0082_auto_20211017_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='IInternoDispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('indice', models.PositiveIntegerField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_asignados', to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='inventario.Dispositivo')),
            ],
            options={
                'verbose_name': 'Asignación Dispositivo - Inventario Interno',
                'verbose_name_plural': 'Asignaciónes Dispositivo - Inventario Interno',
            },
        ),
        migrations.CreateModel(
            name='IInternoEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Estado de inventario interno',
                'verbose_name_plural': 'Estados de inventario interno',
            },
        ),
        migrations.CreateModel(
            name='IIRevisionComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de revisión')),
                ('comentario', models.TextField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisados', to='inventario.Dispositivo')),
            ],
            options={
                'verbose_name': 'Revisión de asignación a inventario interno',
                'verbose_name_plural': 'Revisiónes de asignación a inventario interno',
            },
        ),
        migrations.CreateModel(
            name='InventarioInterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_asignacion', models.CharField(blank=True, db_index=True, editable=False, max_length=10)),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('borrador', models.BooleanField(default=True)),
                ('colaborador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registro', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estados', to='inventario.IInternoEstado')),
            ],
            options={
                'verbose_name': 'Inventario Interno',
                'verbose_name_plural': 'Asignación a Colaboradores',
            },
        ),
        migrations.AddField(
            model_name='desechosalida',
            name='revision_jefe',
            field=models.BooleanField(default=False, verbose_name='jefe_revision'),
        ),
        migrations.AddField(
            model_name='desechosalida',
            name='revision_sub_jefe',
            field=models.BooleanField(default=False, verbose_name='sub_revision'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='autorizado',
            field=models.BooleanField(default=False, verbose_name='autorizado'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='pendiente_autorizar',
            field=models.BooleanField(default=False, verbose_name='pendiente'),
        ),
        migrations.AddField(
            model_name='iirevisioncomentario',
            name='no_asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones', to='inventario.InventarioInterno'),
        ),
        migrations.AddField(
            model_name='iirevisioncomentario',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iinternodispositivo',
            name='no_asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='inventario.InventarioInterno'),
        ),
        migrations.AddField(
            model_name='solicitudmovimiento',
            name='no_inventariointerno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='inventario.InventarioInterno'),
        ),
    ]
