# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2023-01-11 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0083_auto_20220809_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmovimiento',
            name='no_inventariointerno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='inventario.InventarioInterno'),
        ),
    ]
