# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2023-05-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0084_auto_20230110_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadetalle',
            name='precio_subtotal',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='entradadetalle',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
    ]
