# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2023-06-07 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20211017_0942'),
        ('inventario', '0085_auto_20230517_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='prestado_externo_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestado', to='crm.Donante'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='prestado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL),
        ),
    ]
