# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2023-07-26 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0087_solicitudbitacora_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainventario',
            name='caja_repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas_respuestos', to='inventario.SalidaInventario'),
        ),
    ]
