# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2024-06-03 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0089_auto_20231115_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajarepuestos',
            name='salida_asignada',
        ),
        migrations.RemoveField(
            model_name='cajarepuestos',
            name='salida_caja',
        ),
        migrations.AlterField(
            model_name='cajarepuestos',
            name='dispositivo_bueno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispo_malo', to='inventario.Dispositivo'),
        ),
        migrations.AlterField(
            model_name='cajarepuestos',
            name='dispositivo_malo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispo_bueno', to='inventario.Dispositivo'),
        ),
        migrations.AlterField(
            model_name='cajarepuestos',
            name='tecnico_asignado',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
