# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-06-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0090_auto_20240603_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadetalle',
            name='cant_rechazada',
            field=models.PositiveIntegerField(default=0, verbose_name='Veces Rechazadas'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='rechazada',
            field=models.BooleanField(default=False, verbose_name='Rechazada'),
        ),
        migrations.AlterField(
            model_name='entradadetalle',
            name='pendiente_autorizar',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
    ]
