# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-08-20 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0090_auto_20240603_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesechoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('rechazado', models.BooleanField(default=False)),
                ('aprobado_por', models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(default=49, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('desecho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='no_desecho', to='inventario.DesechoSalida')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispo_solicitud_desecho', to='inventario.Dispositivo')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_movimiento_desecho', to='inventario.SolicitudMovimiento')),
            ],
            options={
                'verbose_name_plural': 'Detalles de salida de solicitudes',
                'verbose_name': 'Detalle de salida de solicitud',
            },
        ),
        migrations.RunSQL(
            "ALTER TABLE inventario_desechosolicitud CONVERT TO CHARACTER SET latin1 COLLATE latin1_swedish_ci;",
            reverse_sql=None
        ),
        migrations.AddField(
            model_name='cambioetapa',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='motivo'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='cant_rechazada',
            field=models.PositiveIntegerField(default=0, verbose_name='Veces Rechazadas'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='rechazada',
            field=models.BooleanField(default=False, verbose_name='Rechazada'),
        ),
        migrations.AddField(
            model_name='inventariointerno',
            name='reasignado',
            field=models.BooleanField(default=False, verbose_name='Reasignado'),
        ),
        migrations.AddField(
            model_name='inventariointerno',
            name='reasignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reasignar_inventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entradadetalle',
            name='pendiente_autorizar',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
    ]
