# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-06-24 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0090_auto_20240603_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadetalle',
            name='cant_rechazada',
            field=models.PositiveIntegerField(default=0, verbose_name='Veces Rechazadas'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='rechazada',
            field=models.BooleanField(default=False, verbose_name='Rechazada'),
        ),
        migrations.AddField(
            model_name='inventariointerno',
            name='reasignado',
            field=models.BooleanField(default=False, verbose_name='Reasignado'),
        ),
        migrations.AddField(
            model_name='inventariointerno',
            name='reasignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reasignar_inventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entradadetalle',
            name='pendiente_autorizar',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
    ]
