# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2025-11-24 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211017_1036'),
        ('inventario', '0091_auto_20250820_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_municipio', to='main.Municipio'),
        ),
    ]
