# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2026-03-05 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211017_1036'),
        ('inventario', '0091_auto_20250820_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desechosolicitud',
            options={'verbose_name': 'Salida de dispositivos utiles a desecho', 'verbose_name_plural': 'Salidas de dispositivos utiles a desecho'},
        ),
        migrations.AddField(
            model_name='entrada',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_municipio', to='main.Municipio'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudmovimiento',
            name='complemento',
            field=models.BooleanField(default=False),
        ),
    ]
