# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2026-03-02 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0092_entrada_municipio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desechosolicitud',
            options={'verbose_name': 'Salida de dispositivos utiles a desecho', 'verbose_name_plural': 'Salidas de dispositivos utiles a desecho'},
        ),
        migrations.AddField(
            model_name='solicitudmovimiento',
            name='complemento',
            field=models.BooleanField(default=False),
        ),
    ]
