# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-08-04 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.CharField(max_length=20, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateTimeField()),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='edad')),
                ('pregunta1', models.CharField(blank=True, max_length=150, null=True, verbose_name='¿ Padeces de alguna enfermedad o condición que te coloque en riesgo?')),
                ('pregunta2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Si tu respuesta anterior fue afirmativa por favor explica brevemente la enfermedad o condición que te coloca en riesgo.')),
                ('pregunta3', models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Tienes familiares que vivan contigo en esta época?')),
                ('pregunta4', models.CharField(blank=True, max_length=150, null=True, verbose_name='¿ Has presentado fiebre, tos, dolor de garganta, síntomas gastrointestinales (diarrea y/o vómito)  o dificultad para respirar en la últimas 24 horas?')),
                ('pregunta5', models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Ha cambiado tu situación de salud desde la última vez que respondiste este formulario (solo responder del segundo en adelante)? ')),
                ('pregunta6', models.CharField(blank=True, max_length=150, null=True, verbose_name='Si tu respuesta anterior fue afirmativa por favor explica a continuación:')),
                ('pregunta7', models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Cómo calificas tu estado emocional en este momento?')),
                ('pregunta8', models.CharField(blank=True, max_length=150, null=True, verbose_name='Explica brevemente tu situación mental o emocional en base a tu respuesta a la pregunta anterior.')),
                ('pregunta9', models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Has registrado un cambio en cuanto al número de personas que viven contigo?')),
                ('pregunta10', models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Tienes algún familiar o personas en casa que en las últimas 24 horas haya presentado alguno de los síntomas anteriores?')),
                ('pregunta11', models.CharField(blank=True, max_length=150, null=True, verbose_name='Si tu respuesta anterior fue afirmativa por favor explica a continuación:')),
                ('pregunta12', models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Tuviste contacto con algún caso confirmado o sospechoso de COVID-19?')),
                ('pregunta13', models.CharField(blank=True, max_length=150, null=True, verbose_name='Si tu respuesta es afirmativa, ¿qué medidas tomaste?')),
                ('pregunta14', models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Tiene tu colonia, municipio o comunidad donde vives cordón sanitario?')),
                ('pregunta15', models.CharField(blank=True, max_length=150, null=True, verbose_name='¿ Tienes familiares o personas que vivan contigo en una casa que tenga labores de alta exposición de contacto? (repartidores de alimentos, medicina, o recepcionista?')),
                ('pregunta16', models.CharField(blank=True, max_length=150, null=True, verbose_name='¿ Estás laborando actualmente en las instalaciones de la fundación?')),
                ('pregunta17', models.CharField(blank=True, max_length=150, null=True, verbose_name='¿Qué medidas de seguridad se están tomando dentro de las instalaciones de la fundación?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Históricos de Bienestar',
                'verbose_name': 'Histórico de Bienestar',
            },
        ),
    ]
