# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-08-04 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienestar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='dpi',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
