# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-08-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienestar', '0003_auto_20200806_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='dpi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
