# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-08-15 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienestar', '0005_auto_20200806_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='fecha',
            field=models.DateTimeField(unique=True),
        ),
    ]
