# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mye', '0001_initial'),
        ('escuela', '0002_auto_20161102_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('renovacion', models.BooleanField()),
                ('cooperante', models.ManyToManyField(blank=True, to='mye.Cooperante')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.Escuela')),
            ],
        ),
        migrations.CreateModel(
            name='EquipamientoEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpe.EquipamientoEstado'),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='proyecto',
            field=models.ManyToManyField(blank=True, to='mye.Proyecto'),
        ),
    ]
