# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tpe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='servidor_khan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamiento', to='escuela.Escuela'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tpe.EquipamientoEstado'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='renovacion',
            field=models.BooleanField(default=False),
        ),
    ]
