# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-21 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpe', '0004_auto_20170220_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsoporte',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='equipamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='tpe.Equipamiento'),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='garantia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tpe.Garantia'),
        ),
    ]
