# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe', '0005_auto_20170221_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
