# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-06 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tpe', '0008_auto_20170222_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('comentario', models.TextField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='tpe.Equipamiento')),
            ],
            options={
                'verbose_name_plural': 'Registro de monitoreo',
                'verbose_name': 'Monitoreo',
            },
        ),
    ]
