# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe', '0009_monitoreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamiento',
            name='cooperante',
            field=models.ManyToManyField(blank=True, related_name='equipamientos', to='mye.Cooperante'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='proyecto',
            field=models.ManyToManyField(blank=True, related_name='equipamientos', to='mye.Proyecto'),
        ),
    ]
