# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-07 13:33
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escuela', '0006_escuela_mapa'),
        ('tpe', '0010_auto_20170321_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Tipos de dispositivo',
                'verbose_name': 'Tipo de dispositivo',
            },
        ),
        migrations.CreateModel(
            name='TicketReparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage', models.PositiveIntegerField()),
                ('falla_reportada', models.TextField()),
                ('falla_encontrada', models.TextField(blank=True, null=True)),
                ('solucion_detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reparaciones de garantías',
                'verbose_name': 'Reparación de garantía',
            },
        ),
        migrations.CreateModel(
            name='TicketReparacionEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Estados de reparación',
                'verbose_name': 'Estado de reparación',
            },
        ),
        migrations.CreateModel(
            name='TicketReparacionRepuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe.TicketReparacion')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe.DispositivoTipo')),
            ],
            options={
                'verbose_name_plural': 'Respuestos para reparación',
                'verbose_name': 'Respuesto para reparación',
            },
        ),
        migrations.CreateModel(
            name='TicketReparacionTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Tipos de reparación',
                'verbose_name': 'Tipo de reparación',
            },
        ),
        migrations.CreateModel(
            name='TicketTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Transportes de garantíass',
                'verbose_name': 'Transporte de garantías',
            },
        ),
        migrations.CreateModel(
            name='TicketTransporteTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipos de transporte de garantías',
                'verbose_name': 'Tipo de transporte de garantías',
            },
        ),
        migrations.AlterModelOptions(
            name='monitoreo',
            options={'verbose_name': 'Monitoreo', 'verbose_name_plural': 'Registros de monitoreo'},
        ),
        migrations.AlterModelOptions(
            name='ticketsoporte',
            options={'verbose_name': 'Ticket de soporte', 'verbose_name_plural': 'Tickets de soporte'},
        ),
        migrations.RenameField(
            model_name='ticketregistro',
            old_name='usuario',
            new_name='creado_por',
        ),
        migrations.RemoveField(
            model_name='ticketregistro',
            name='costo_envio',
        ),
        migrations.RemoveField(
            model_name='ticketregistro',
            name='costo_reparacion',
        ),
        migrations.AddField(
            model_name='garantia',
            name='por_funsepa',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketregistro',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketsoporte',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_cerrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketsoporte',
            name='contacto_reporta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='escuela.EscContacto'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='abierto_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_abiertos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickettransporte',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe.TicketSoporte'),
        ),
        migrations.AddField(
            model_name='tickettransporte',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe.TicketTransporteTipo'),
        ),
        migrations.AddField(
            model_name='tickettransporte',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketreparacion',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe.TicketReparacionEstado'),
        ),
        migrations.AddField(
            model_name='ticketreparacion',
            name='solucion_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpe.TicketReparacionTipo'),
        ),
        migrations.AddField(
            model_name='ticketreparacion',
            name='tecnico_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketreparacion',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe.TicketSoporte'),
        ),
        migrations.AddField(
            model_name='ticketreparacion',
            name='tipo_dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe.DispositivoTipo'),
        ),
    ]
