# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-07 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tpe', '0011_auto_20170407_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreparacion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketreparacion',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticketreparacion',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones', to='tpe.TicketSoporte'),
        ),
    ]
