# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-17 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpe', '0012_auto_20170407_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketreparacionrepuesto',
            options={'verbose_name': 'Repuesto para reparación', 'verbose_name_plural': 'Repuestos para reparación'},
        ),
        migrations.AddField(
            model_name='ticketreparacionrepuesto',
            name='autorizado',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketreparacionrepuesto',
            name='reparacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='tpe.TicketReparacion'),
        ),
    ]
