# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-24 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe', '0015_auto_20170421_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
