# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-09 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpe', '0017_auto_20170605_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreparacion',
            name='tecnico_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
