# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-09 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpe', '0020_visitamonitoreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitamonitoreo',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitas_contactos', to='escuela.EscContacto'),
        ),
        migrations.AlterField(
            model_name='visitamonitoreo',
            name='fotos_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link a fotografias'),
        ),
        migrations.AlterField(
            model_name='visitamonitoreo',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitas_soporte', to='tpe.TicketSoporte'),
        ),
    ]
