# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2024-03-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe', '0023_equipamiento_tablet_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='no_referencia',
            field=models.IntegerField(default=0),
        ),
    ]
