# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-06-17 04:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tpe', '0024_equipamiento_no_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSoporteTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(verbose_name='Tipo de soporte')),
                ('creado_por', models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de soporte de ticket',
                'verbose_name_plural': 'Tipos de soporte de tickets',
            },
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='no_referencia',
            field=models.IntegerField(default=0, verbose_name='Numero de referencia de entrega'),
        ),
        migrations.AddField(
            model_name='ticketreparacion',
            name='tipo_soporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpe.TipoSoporteTicket'),
        ),
    ]
