# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EscuelaCooperante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_activacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_anulacion', models.DateField(blank=True, null=True)),
                ('cooperante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_equipada', to='mye.Cooperante')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_cooperante', to='escuela.Escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
