# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='formulario',
            field=models.BooleanField(default=False),
        ),
    ]
