# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escuela', '0003_auto_20161115_1406'),
        ('mye', '0002_solicitud_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('jornada', models.IntegerField(default=1)),
                ('alumna', models.IntegerField()),
                ('alumno', models.IntegerField()),
                ('maestra', models.IntegerField()),
                ('maestro', models.IntegerField()),
                ('total_alumno', models.IntegerField(blank=True, null=True)),
                ('total_maestro', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validacion', to='escuela.Escuela')),
                ('requisito', models.ManyToManyField(blank=True, to='mye.Requisito')),
            ],
            options={
                'verbose_name': 'Validacion',
                'verbose_name_plural': 'Validaciones',
            },
        ),
        migrations.CreateModel(
            name='ValidacionComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='mye.Validacion')),
            ],
            options={
                'verbose_name': 'Comentario de validación',
                'verbose_name_plural': 'Comentarios de validación',
            },
        ),
        migrations.CreateModel(
            name='ValidacionTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de validación',
                'verbose_name_plural': 'Tipos de validación',
            },
        ),
        migrations.CreateModel(
            name='ValidacionVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Versión de validación',
                'verbose_name_plural': 'Versiones de validación',
            },
        ),
        migrations.AddField(
            model_name='validacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mye.ValidacionTipo'),
        ),
        migrations.AddField(
            model_name='validacion',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mye.ValidacionVersion'),
        ),
    ]
