# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mye', '0002_auto_20161010_1832'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='escuelacooperante',
            unique_together=set([]),
        ),
    ]
