# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_escuela_cooperante_asignado'),
        ('mye', '0003_auto_20161011_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscuelaProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_activacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_anulacion', models.DateField(blank=True, null=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_proyecto', to='escuela.Escuela')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_equipada', to='mye.Proyecto')),
            ],
        ),
    ]
