# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mye', '0003_auto_20170203_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacionversion',
            name='requisito',
            field=models.ManyToManyField(to='mye.Requisito'),
        ),
    ]
