# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-08 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mye', '0004_validacionversion_requisito'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacion',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='validacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='validacioncomentario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
