# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_poblacion'),
        ('mye', '0005_requisito_solicitudversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('jornada', models.IntegerField()),
                ('edf', models.BooleanField()),
                ('lab_actual', models.BooleanField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.Escuela')),
                ('medio', models.ManyToManyField(to='mye.Medio')),
                ('requisito', models.ManyToManyField(to='mye.Requisito')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.AlterModelOptions(
            name='solicitudversion',
            options={'verbose_name': 'Versión de solicitud', 'verbose_name_plural': 'Versiones de solicitud'},
        ),
        migrations.AlterField(
            model_name='escuelacooperante',
            name='cooperante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_asignada', to='mye.Cooperante'),
        ),
        migrations.AlterField(
            model_name='escuelaproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuela_asignada', to='mye.Proyecto'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mye.SolicitudVersion'),
        ),
    ]
