# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mye', '0005_auto_20170208_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validacion',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='validacion',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
