# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-21 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mye', '0006_auto_20170213_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacion',
            name='fecha_equipamiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
