# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_poblacion'),
        ('mye', '0006_auto_20161012_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='poblacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poblacion', to='escuela.Poblacion'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitud', to='escuela.Escuela'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='medio',
            field=models.ManyToManyField(blank=True, to='mye.Medio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='requisito',
            field=models.ManyToManyField(blank=True, to='mye.Requisito'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitud', to='mye.SolicitudVersion'),
        ),
    ]
