# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mye', '0007_auto_20161024_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumna', models.IntegerField()),
                ('alumno', models.IntegerField()),
                ('maestra', models.IntegerField()),
                ('maestro', models.IntegerField()),
                ('total_alumno', models.IntegerField(blank=True, null=True)),
                ('total_maestro', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='poblacion',
        ),
        migrations.AddField(
            model_name='poblacion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poblacion', to='mye.Solicitud'),
        ),
    ]
