# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_escpoblacion'),
        ('mye', '0007_validacion_fecha_equipamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='poblacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='escuela.EscPoblacion'),
        ),
        migrations.AlterField(
            model_name='solicitudversion',
            name='requisito',
            field=models.ManyToManyField(blank=True, to='mye.Requisito'),
        ),
        migrations.AlterField(
            model_name='validacionversion',
            name='requisito',
            field=models.ManyToManyField(blank=True, to='mye.Requisito'),
        ),
    ]
