# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mye', '0008_auto_20161024_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poblacion',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='alumna',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='alumno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='maestra',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='maestro',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='total_alumno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='total_maestro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Poblacion',
        ),
    ]
