# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mye', '0009_auto_20170321_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='alumna',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='maestra',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='maestro',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='total_alumno',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='total_maestro',
        ),
    ]
