# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mye', '0013_solicitudcomentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCooperante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mye.Cooperante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de cooperante',
                'verbose_name_plural': 'Usuarios de cooperantes',
            },
        ),
    ]
