# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2025-02-07 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mye', '0015_auto_20211017_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='grupos_familia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Grupos familias'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='prom_mat_quinto_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Promedio matemática quinto primaria'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='prom_mat_seg_b',
            field=models.FloatField(blank=True, null=True, verbose_name='Promedio matemática segundo básico'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='prom_mat_seg_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Promedio matemática segundo primaria'),
        ),
        migrations.AddField(
            model_name='validacion',
            name='grupos_familia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Grupos familias'),
        ),
        migrations.AddField(
            model_name='validacion',
            name='internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validacion',
            name='prom_mat_quinto_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Promedio matemática quinto primaria'),
        ),
        migrations.AddField(
            model_name='validacion',
            name='prom_mat_seg_b',
            field=models.FloatField(blank=True, null=True, verbose_name='Promedio matemática segundo básico'),
        ),
        migrations.AddField(
            model_name='validacion',
            name='prom_mat_seg_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Promedio matemática segundo primaria'),
        ),
    ]
