# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2024-02-05 14:48

from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuela', '0011_auto_20211017_1152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

        ('cyd', '0032_auto_20231209_2145'),

    ]

    operations = [
        migrations.CreateModel(
            name='AreaEvaluada',

            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_evaluada', models.CharField(max_length=30, verbose_name='area_evaluada')),
            ],
            options={
                'verbose_name_plural': 'Areas Evaluadas',
                'verbose_name': 'Area Evaluada',
            },
        ),
        migrations.CreateModel(
            name='AsignacionPregunta',

            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondido', models.BooleanField(default=False)),
                ('fecha_incio_evaluacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha incio evaluacion')),
                ('fecha_fin_evaluacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha fin evaluacion')),
                ('evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluado', to='cyd.Participante')),
            ],
            options={
                'verbose_name_plural': 'Asignacion de preguntas',
                'verbose_name': 'Asignacion de pregunta',
            },
        ),
        migrations.CreateModel(
            name='DispositivoParticipantes',

            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo_dispositivo')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo_sistema_operativo')),
                ('participante_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluado_dispositivo', to='cyd.Participante')),
            ],
            options={
                'verbose_name_plural': 'Informacion de dispositivos',
                'verbose_name': 'Informacion de dispositivo',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',

            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.CharField(max_length=40, verbose_name='evaluacion')),
                ('tipo_evaluacion', models.CharField(choices=[('ponderada', 'Ponderada'), ('no ponderada', 'No Ponderada')], default='no ponderada', max_length=40, verbose_name='Tipo de evaluacion')),
            ],
            options={
                'verbose_name_plural': 'Evaluaciones',
                'verbose_name': 'Evaluación',
            },
        ),
        migrations.CreateModel(
            name='Formulario',

            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('fecha_inicio_formulario', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha incio formulario')),
                ('fecha_fin_formulario', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha fin formulario')),
                ('fecha_creacion_formulario', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion formulario')),

                ('area_evaluada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.AreaEvaluada')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_escuela', to='escuela.Escuela')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.Evaluacion')),

                ('formulario_creado_por', models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Formularios',
                'verbose_name': 'Formulario',

            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200, verbose_name='Pregunta')),
                ('estado', models.BooleanField(default=True)),
                ('ponderacion', models.IntegerField(blank=True, null=True)),
                ('area_evaluada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.AreaEvaluada')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.Evaluacion')),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
                'verbose_name': 'Pregunta',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',

            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(verbose_name='respuesta')),
            ],
            options={

                'verbose_name_plural': 'Respuestas',
                'verbose_name': 'Respuesta',
            },
        ),
        migrations.CreateModel(
            name='SeccionPregunta',

            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion_pregunta', models.CharField(max_length=40, verbose_name='seccion_pregunta')),
                ('activo', models.BooleanField(default=True)),
                ('instrucciones', models.TextField(verbose_name='respuesta')),
                ('area_evaluada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.AreaEvaluada')),
            ],
            options={
                'verbose_name_plural': 'Secciones de Preguntas',
                'verbose_name': 'Sección Pregunta',
            },
        ),
        migrations.CreateModel(
            name='TipoRespuesta',

            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_respuesta', models.CharField(max_length=10, verbose_name='Tipo_de_respuesta')),
            ],
            options={
                'verbose_name_plural': 'Tipos de respuestas',
                'verbose_name': 'Tipo de respuesta',

            },
        ),
        migrations.AddField(
            model_name='respuesta',
            name='tipo_respuesta',

            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.TipoRespuesta'),

        ),
        migrations.AddField(
            model_name='pregunta',
            name='seccion_pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.SeccionPregunta'),

        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo_respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_de_pregunta', to='Evaluacion.TipoRespuesta'),

        ),
        migrations.AddField(
            model_name='asignacionpregunta',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.Formulario'),

        ),
        migrations.AddField(
            model_name='asignacionpregunta',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.Pregunta'),
        ),
        migrations.AddField(
            model_name='asignacionpregunta',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.Respuesta'),

        ),
    ]
