# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2024-07-26 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyd', '0033_sede_fecha_finalizacion'),
        ('Evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoFormulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('preguntas', models.ManyToManyField(related_name='Preguntas_Asignadas', to='Evaluacion.AsignacionPregunta')),
            ],
            options={
                'verbose_name': 'Estado de formulario',
                'verbose_name_plural': 'Estado de formularios',
            },
        ),
        migrations.AddField(
            model_name='formulario',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cyd.Sede'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Capacitador', to=settings.AUTH_USER_MODEL),
        ),
    ]
